import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import matrixSource from '../docs/payment-support-matrix.json';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
export const paymentSupportMatrixPath = join(
  repoRoot,
  'docs',
  'PAYMENT_SUPPORT_MATRIX.md'
);

const transportStatuses = ['supported', 'unsupported', 'custom'] as const;
type TransportStatus = (typeof transportStatuses)[number];

export type PaymentSupportRow = {
  id: string;
  protocol: string;
  sdk: string;
  scheme: string;
  network: string;
  buyer: string;
  seller: string;
  facilitator: string;
  transport: {
    invoke: TransportStatus;
    stream: TransportStatus;
    task: TransportStatus;
  };
  storage: string;
  status: string;
  limitations: string;
};

export type PaymentSupportMatrix = {
  schemaVersion: 1;
  sdkVersions: {
    x402: string;
    mppx: string;
  };
  rows: PaymentSupportRow[];
};

function assertNonEmptyString(
  value: unknown,
  path: string
): asserts value is string {
  if (typeof value !== 'string' || value.trim().length === 0) {
    throw new Error(`${path} must be a non-empty string`);
  }
}

function assertTransportStatus(
  value: unknown,
  path: string
): asserts value is TransportStatus {
  if (!transportStatuses.includes(value as TransportStatus)) {
    throw new Error(
      `${path} must be one of ${transportStatuses.map(status => `"${status}"`).join(', ')}`
    );
  }
}

export function validatePaymentSupportMatrix(
  value: unknown
): PaymentSupportMatrix {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Payment support matrix source must be an object');
  }
  const source = value as Record<string, unknown>;
  if (source.schemaVersion !== 1) {
    throw new Error('Payment support matrix schemaVersion must be 1');
  }
  if (
    !source.sdkVersions ||
    typeof source.sdkVersions !== 'object' ||
    Array.isArray(source.sdkVersions)
  ) {
    throw new Error('Payment support matrix sdkVersions must be an object');
  }
  const sdkVersions = source.sdkVersions as Record<string, unknown>;
  assertNonEmptyString(sdkVersions.x402, 'sdkVersions.x402');
  assertNonEmptyString(sdkVersions.mppx, 'sdkVersions.mppx');
  if (!Array.isArray(source.rows) || source.rows.length === 0) {
    throw new Error('Payment support matrix rows must be a non-empty array');
  }

  const ids = new Set<string>();
  source.rows.forEach((rawRow, index) => {
    if (!rawRow || typeof rawRow !== 'object' || Array.isArray(rawRow)) {
      throw new Error(`rows[${index}] must be an object`);
    }
    const row = rawRow as Record<string, unknown>;
    for (const field of [
      'id',
      'protocol',
      'sdk',
      'scheme',
      'network',
      'buyer',
      'seller',
      'facilitator',
      'storage',
      'status',
      'limitations',
    ] as const) {
      assertNonEmptyString(row[field], `rows[${index}].${field}`);
    }
    if (ids.has(row.id as string)) {
      throw new Error(`Duplicate payment support row id "${String(row.id)}"`);
    }
    ids.add(row.id as string);
    if (
      !row.transport ||
      typeof row.transport !== 'object' ||
      Array.isArray(row.transport)
    ) {
      throw new Error(`rows[${index}].transport must be an object`);
    }
    const transport = row.transport as Record<string, unknown>;
    assertTransportStatus(transport.invoke, `rows[${index}].transport.invoke`);
    assertTransportStatus(transport.stream, `rows[${index}].transport.stream`);
    assertTransportStatus(transport.task, `rows[${index}].transport.task`);
  });

  return value as PaymentSupportMatrix;
}

function escapeCell(value: string): string {
  return value.replaceAll('|', '\\|').replaceAll('\n', '<br>');
}

function transportLabel(row: PaymentSupportRow): string {
  const label = (status: TransportStatus): string => {
    if (status === 'supported') return 'yes';
    if (status === 'unsupported') return 'no';
    return 'custom';
  };
  return [
    `invoke: ${label(row.transport.invoke)}`,
    `stream/SSE: ${label(row.transport.stream)}`,
    `task: ${label(row.transport.task)}`,
  ].join('; ');
}

export function renderPaymentSupportMatrix(
  source: PaymentSupportMatrix
): string {
  const rows = source.rows.map(row =>
    [
      `${row.protocol}<br>${row.sdk}`,
      row.scheme,
      row.network,
      row.buyer,
      row.seller,
      row.facilitator,
      transportLabel(row),
      row.storage,
      `**${row.status}.** ${row.limitations}`,
    ]
      .map(escapeCell)
      .join(' | ')
  );

  return `# Payment support matrix

<!-- Generated by scripts/generate-payment-support-matrix.ts from docs/payment-support-matrix.json. Do not edit directly. -->

This matrix describes Lucid's shipped payment surface. “Built in” means Lucid
registers and coordinates the implementation; it does not remove the need for
credentials, accounts, network access, or provider configuration.

- x402 SDK cohort: exact \`${source.sdkVersions.x402}\`
- MPP SDK: exact \`mppx ${source.sdkVersions.mppx}\`
- Durable adapters coordinate replicas and survive restarts. Process-local
  defaults are intended for development and single-process deployments.

| Protocol / SDK | Scheme / method | Network | Buyer | Seller | Facilitator dependency | Transport | Storage / durability | Status / limitations |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
${rows.map(row => `| ${row} |`).join('\n')}

Regenerate this document with \`bun run docs:payment-support\`. CI verifies the
generated file, SDK pins, package export maps, and packed storage imports with
\`bun run check:payment-support\`.
`;
}

async function readCatalogVersions(): Promise<{
  x402: string;
  mppx: string;
}> {
  const manifest = JSON.parse(
    await readFile(join(repoRoot, 'package.json'), 'utf8')
  ) as {
    workspaces?: {
      catalog?: Record<string, string>;
    };
  };
  const catalog = manifest.workspaces?.catalog;
  const x402Packages = [
    '@x402/core',
    '@x402/extensions',
    '@x402/fetch',
    '@x402/evm',
    '@x402/svm',
  ];
  const x402Versions = new Set(x402Packages.map(name => catalog?.[name]));
  if (x402Versions.size !== 1 || x402Versions.has(undefined)) {
    throw new Error('The x402 catalog cohort is missing or not pinned exactly');
  }
  const x402 = [...x402Versions][0]!;
  const mppx = catalog?.mppx;
  if (!mppx) throw new Error('The mppx catalog pin is missing');
  return { x402, mppx };
}

export async function generatePaymentSupportMatrix(options: {
  check: boolean;
}): Promise<void> {
  const source = validatePaymentSupportMatrix(matrixSource);
  const catalogVersions = await readCatalogVersions();
  if (
    source.sdkVersions.x402 !== catalogVersions.x402 ||
    source.sdkVersions.mppx !== catalogVersions.mppx
  ) {
    throw new Error(
      `Payment support SDK pins are stale: source has x402 ${source.sdkVersions.x402} and mppx ${source.sdkVersions.mppx}; catalog has x402 ${catalogVersions.x402} and mppx ${catalogVersions.mppx}`
    );
  }
  const rendered = renderPaymentSupportMatrix(source);
  if (options.check) {
    const current = await readFile(paymentSupportMatrixPath, 'utf8').catch(
      () => undefined
    );
    if (current !== rendered) {
      throw new Error(
        'Generated payment support matrix is stale. Run "bun run docs:payment-support".'
      );
    }
    console.info('Payment support matrix and SDK pins are current.');
    return;
  }
  await writeFile(paymentSupportMatrixPath, rendered);
  console.info('Generated docs/PAYMENT_SUPPORT_MATRIX.md.');
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  const unknown = args.filter(argument => argument !== '--check');
  if (unknown.length > 0) {
    throw new Error(`Unknown arguments: ${unknown.join(', ')}`);
  }
  await generatePaymentSupportMatrix({ check: args.includes('--check') });
}
