// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiAgentsByAgentIdData, DeleteApiAgentsByAgentIdErrors, DeleteApiAgentsByAgentIdResponses, GetAgentsByAgentIdEntrypointsData, GetAgentsByAgentIdEntrypointsErrors, GetAgentsByAgentIdEntrypointsResponses, GetAgentsByAgentIdWellKnownAgentJsonData, GetAgentsByAgentIdWellKnownAgentJsonErrors, GetAgentsByAgentIdWellKnownAgentJsonResponses, GetApiAgentsByAgentIdData, GetApiAgentsByAgentIdErrors, GetApiAgentsByAgentIdResponses, GetApiAgentsData, GetApiAgentsResponses, GetHealthData, GetHealthResponses, PostAgentsByAgentIdEntrypointsByKeyInvokeData, PostAgentsByAgentIdEntrypointsByKeyInvokeErrors, PostAgentsByAgentIdEntrypointsByKeyInvokeResponses, PostApiAgentsData, PostApiAgentsErrors, PostApiAgentsResponses, PutApiAgentsByAgentIdData, PutApiAgentsByAgentIdErrors, PutApiAgentsByAgentIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List agents
 *
 * List all agents for the current owner with pagination.
 */
export const getApiAgents = <ThrowOnError extends boolean = false>(options?: Options<GetApiAgentsData, ThrowOnError>) => (options?.client ?? client).get<GetApiAgentsResponses, unknown, ThrowOnError>({ url: '/api/agents', ...options });

/**
 * Create agent
 *
 * Create a new agent with the given configuration.
 */
export const postApiAgents = <ThrowOnError extends boolean = false>(options: Options<PostApiAgentsData, ThrowOnError>) => (options.client ?? client).post<PostApiAgentsResponses, PostApiAgentsErrors, ThrowOnError>({
    url: '/api/agents',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete agent
 *
 * Delete an agent by its ID.
 */
export const deleteApiAgentsByAgentId = <ThrowOnError extends boolean = false>(options: Options<DeleteApiAgentsByAgentIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiAgentsByAgentIdResponses, DeleteApiAgentsByAgentIdErrors, ThrowOnError>({ url: '/api/agents/{agentId}', ...options });

/**
 * Get agent
 *
 * Get an agent by its ID.
 */
export const getApiAgentsByAgentId = <ThrowOnError extends boolean = false>(options: Options<GetApiAgentsByAgentIdData, ThrowOnError>) => (options.client ?? client).get<GetApiAgentsByAgentIdResponses, GetApiAgentsByAgentIdErrors, ThrowOnError>({ url: '/api/agents/{agentId}', ...options });

/**
 * Update agent
 *
 * Update an existing agent. Only provided fields will be updated.
 */
export const putApiAgentsByAgentId = <ThrowOnError extends boolean = false>(options: Options<PutApiAgentsByAgentIdData, ThrowOnError>) => (options.client ?? client).put<PutApiAgentsByAgentIdResponses, PutApiAgentsByAgentIdErrors, ThrowOnError>({
    url: '/api/agents/{agentId}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get agent manifest
 *
 * Get the agent manifest/card in A2A-compatible format.
 */
export const getAgentsByAgentIdWellKnownAgentJson = <ThrowOnError extends boolean = false>(options: Options<GetAgentsByAgentIdWellKnownAgentJsonData, ThrowOnError>) => (options.client ?? client).get<GetAgentsByAgentIdWellKnownAgentJsonResponses, GetAgentsByAgentIdWellKnownAgentJsonErrors, ThrowOnError>({ url: '/agents/{agentId}/.well-known/agent.json', ...options });

/**
 * List entrypoints
 *
 * List all entrypoints for an agent.
 */
export const getAgentsByAgentIdEntrypoints = <ThrowOnError extends boolean = false>(options: Options<GetAgentsByAgentIdEntrypointsData, ThrowOnError>) => (options.client ?? client).get<GetAgentsByAgentIdEntrypointsResponses, GetAgentsByAgentIdEntrypointsErrors, ThrowOnError>({ url: '/agents/{agentId}/entrypoints', ...options });

/**
 * Invoke entrypoint
 *
 * Execute an agent entrypoint synchronously and return the result.
 */
export const postAgentsByAgentIdEntrypointsByKeyInvoke = <ThrowOnError extends boolean = false>(options: Options<PostAgentsByAgentIdEntrypointsByKeyInvokeData, ThrowOnError>) => (options.client ?? client).post<PostAgentsByAgentIdEntrypointsByKeyInvokeResponses, PostAgentsByAgentIdEntrypointsByKeyInvokeErrors, ThrowOnError>({
    url: '/agents/{agentId}/entrypoints/{key}/invoke',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health check
 *
 * Check if the service is running and healthy.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
