import type { AgentKitConfig } from "@lucid-agents/agent-kit";
{{FEATURE_IMPORTS}}
{{ADAPTER_IMPORTS}}

{{FEATURE_PRE_APP}}

{{ADAPTER_CONFIG_OVERRIDES}}

{{ADAPTER_APP_CREATION}}

{{FEATURE_POST_APP}}

{{FEATURE_ENTRYPOINTS}}

{{ADAPTER_ENTRYPOINT_REGISTRATION}}

{{FEATURE_EXPORTS}}

{{ADAPTER_EXPORTS}}
